### ISSUE TITLE
Add github or twitter handles to the session titles.

### ISSUE THREAD

**Issue by thomasdarimont** [JCrete/jcrete2016#2]
To follow up it would be nice to see who actually conveyed a session :)

**Comment by rgra** [comment]
Thomas, you know how difficult it is to gather all the material. I added notes to the main page on how to add material, but it's up to everyone to follow it or not.

**Comment by thomasdarimont** [comment]
Okay, no worries - thanks for taking care of materials!

Cheers,
Thomas
